PlaidCloud/plaid-utilities

plaidcloud/utilities/remote/dimension.py
=> ch6121 - fixes and methods to build diagnostic repair utilities

plaidcloud/utilities/remote/dimension.py
Quick change for Axalta and Mike
=> Remove node as index in hierarchy_table/dimension_table functions

plaidcloud/utilities/remote/dimension.py
This is the new consolidate functionality. It does not store the new values as that would potentially overwrite important data.  Data is returned in the form of a dataframe as mots likely will need processing in UDF.
=> ch6410 - renamed and final version using a dataframe for processing

plaidcloud/utilities/remote/dimension.py
Added the dimension UUID as property to dimension proxy class. Need it for diagnostic programs.
=> Expose the dim UUID (duid) to the client code

plaidcloud/utilities/remote/dimension.py, plaidcloud/utilities/stringtransforms.py
=> Revert pickle

plaidcloud/utilities/data_helpers.py
This fixes the problem seen in Lexmark, it seems sensible, but I don't write UDFs so don't know what the expectation is.
=> ch6836 - Handle pandas NA type in data_helpers methods

plaidcloud/utilities/convert_encoding.py
Allowing the chunksize to increase on this error seems to rectify the issue.
=> ch6837 Convert encoding - increase chunk on 'unexpected end of data'

plaidcloud/utilities/frame_manager.py, plaidcloud/utilities/remote/dimension.py
=> Ch6249 - Fix to allow dimension instantiation from dimension Id

plaidcloud/utilities/frame_manager.py, plaidcloud/utilities/remote/dimension.py, plaidcloud/utilities/sql_expression.py
I know this is going to be a little controversial, but I've made some amends to `apply_rules`
=> apply_rule/apply_rules updates

plaidcloud/utilities/frame_manager.py
A bit of fettling, improved time from minutes to 20s locally. I *think* it still works the same.
=> ch6249 Speed up apply_rules

plaidcloud/utilities/remote/dimension.py
=> Add only_properties param to `get_all_properties`

plaidcloud/utilities/remote/dimension.py, plaidcloud/utilities/sql_expression.py
Proxy for set_node_properties on dimension
SQLAlchemy version of frame_manager allocate method for sql_expression
=> Ch6249 - Additional methods

plaidcloud/utilities/sql_expression.py
Allow variable application to be disabled for the parts of sql_expression data_explorer needs.
There will be another data_explorer PR once this is in - if we try to do them both at the same time, linting will fail
=> disable_variables flag

plaidcloud/utilities/remote/dimension.py, plaidcloud/utilities/sql_expression.py
Also rework of Columns and passthrough in sql allocation
=> Ch6249 Allocation - allow to get leaves for multiple nodes in one RPC

plaidcloud/utilities/sql_expression.py
* Columns were not being picked out by field name
=> Fix missing fields in allocation

Jenkinsfile
Reference: [ch6860](https://app.clubhouse.io/plaidcloud/story/6860/plaid-utilities-plaid-rpc-no-longer-run-the-unit-tests)
=> run pylint and report results

plaidcloud/utilities/frame_manager.py, requirements.txt
For use with plaid PR https://github.com/PlaidCloud/plaid/pull/3493
=> Use asyncio and orjson to convert JSON to CSV

plaidcloud/utilities/frame_manager.py
I guess not all aio libraries are that great, aiocsv is not performant, nor does it read csvs in the same way that the standard lib does. moves the conversion back to synchronous code that can be called in an executor
=> Put this back to sync code, aiocsv is junk

plaidcloud/utilities/analyze_table.py, plaidcloud/utilities/query.py, requirements.txt
Send "render_postcompile" to behave as before. Don't pin SQLAlchemy
=> Fix sqlalchemy compile

plaidcloud/utilities/stringtransforms.py
* What was the string we were trying to replace variables in
This is currently raising Exception in IO, but no idea why. The same step runs fine for me locally.
=> Give further detail when apply_variables does not work

plaidcloud/utilities/frame_manager.py
* Well, that's not gonna cause a problem
=> xlrd3 renames `datemode` to `date_mode`

plaidcloud/utilities/sql_expression.py
* Include *_source versions of dimensions which may be re-allocated
=> ch7490 Option to include source columns with allocation

plaidcloud/utilities/frame_manager.py, plaidcloud/utilities/tests/test_hasher.py, requirements.txt
So, it seems XLRD3 is slightly faster than openpyxl for some things, specifically iterating a whole document to convert to CSV. We already use openpyxl for some other things such as to get a list of worksheets quickly so it's not going away. Here, I just add the equivalent convert_to_csv method in case we may want to use it in future.
=> Ch7410 - XLRD/OpenPYXL

plaidcloud/utilities/remote/dimension.py
* Adds the option to include/exclude inherited columns
=> Update hierarchy_table remote dimension method

.gitignore, plaidcloud/utilities/analyze_table.py, plaidcloud/utilities/sql_expression.py, plaidcloud/utilities/sqlalchemy_functions.py, plaidcloud/utilities/stringtransforms.py
Reverts PlaidCloud/plaid-utilities#87
Table explorer facets are broken and I need to push a change to Beta
=> Revert "Ch7980"

plaidcloud/utilities/sql_expression.py
Distinguish between returning "This column should be NULL" and "This column shouldn't be included"
=> Fix the update transform issue

plaidcloud/utilities/query.py
Prevents duplication of in-memory work when saving a dataframe back to plaid.
Tidies up module, removes six and unused imports
=> Speed up save dataframe

plaidcloud/utilities/frame_manager.py
Includes row and column in Exception when converting Excel to CSV.
Some linting things
=> Better excel exception

plaidcloud/utilities/sqlalchemy_functions.py
=> Fix safe round to allow one or more arguments

plaidcloud/utilities/sqlalchemy_functions.py
This was corrupting dates in it's current format.
=> Fix safe to timestamp

plaidcloud/utilities/remote/dimension.py
* Defaulted to ON for now until loading issues resolved
=> Make Dataframe loading optional

plaidcloud/utilities/color.py, plaidcloud/utilities/sqlalchemy_functions.py
Don't perform to_timestamp if it is an interval
=> Fix extract interval datatype

plaidcloud/utilities/sqlalchemy_functions.py, plaidcloud/utilities/tests/test_sqlalchemy_functions.py
Adds both zfill function and normalize_whitespace function. They've been tested by making sure they compile to sql that looks right.
=> Sql zfill and normalize_whitespace

plaidcloud/utilities/sqlalchemy_functions.py
Makes numericize only allow minus signs (or plus signs) at the beginning of a string
=> Numericize changes

plaidcloud/utilities/sqlalchemy_functions.py, plaidcloud/utilities/tests/test_sqlalchemy_functions.py
Quite a complicated expression to either parse a datetime, or parse an interval string that may have been spat out from Greenplum.
=> Import an interval column

plaidcloud/utilities/sqlalchemy_functions.py, plaidcloud/utilities/tests/test_sqlalchemy_functions.py
Remove the BindParameter produced on old line 1239, make produced SQL shorter
=> Fix string_to_array Databend

plaidcloud/utilities/frame_manager.py
Prevents settingwithcopywarning from pandas.
=> Fix warnings on Allocation when include_once is False

plaidcloud/utilities/sql_expression.py
Have to use SQLAlchemy expressions for true() and false() in 2.0
=> Fix allocations for SQLALchemy 2.0

plaidcloud/utilities/query.py
Reports a more helpful error message than the pyarrow error.
=> Sc 19172 - Check for same datatype in pandas column

liccheck.ini, plaidcloud/utilities/query.py
Allows UDFs to access source and tables as `con.udf.source[0]` `con.udf.target[0]` `con.udf.variables['myvariable']`
=> Changes for UDF Parameters

plaidcloud/utilities/query.py
Also exposes variables on the PlaidConnection
=> Apply variables to udf tables/variables

liccheck.ini, plaidcloud/utilities/query.py, requirements.txt
And fix for identifying mixed type columns when saving from dataframes
=> SQLAlchemy 2.0

plaidcloud/utilities/frame_manager.py, requirements.txt
* Excel to CSV now requires calamine engine - python-calamine
=> Removes XLRD and OpenPyExcel requirements
